### ISSUE TITLE
Grey not the ideal color for the license badge

### ISSUE THREAD

**Issue by ssokolow** [arcnmx/cargo-clippy#18]
The grey you used for the "MIT" portion of the license badge gives the wrong impression when viewed out of the corner of your eye. (Grey means "test process errored out" on sites like Travis.CI)

For people who have gotten in the habit of seeing the row of badges as a row of indicator lights, that disconnect between perceived convention and actual meaning is uncomfortable.

Might I suggest blue instead? (Green, yellow, orange, and red also have pre-existing "status indication" meanings while blue seems to be a common choice various badge providers have settled on for information which doesn't embody an objective good/bad evaluation like the current release version, license, etc.)

**Comment by hugovk** [comment]
I agree.

PR https://github.com/arcnmx/cargo-clippy/pull/20 created for this.
