### ISSUE TITLE
cargo-clippy passes wrong arguments to rustc

### ISSUE THREAD

**Issue by untitaker** [arcnmx/cargo-clippy#8]
See https://travis-ci.org/untitaker/mysteryshack/jobs/96356699#L519

> extra arguments to `rustc` can only be passed to one target, consider filtering the package by passing e.g. `--lib` or `--bin NAME` to specify a single target

_rust nightly version: 2015-12-11_

Just run `cargo clippy` on https://github.com/untitaker/mysteryshack

**Comment by arcnmx** [comment]
`cargo clippy --lib` works fine. You have to specify what you want to run clippy on when it's ambiguous, just as the error message says.
